### ISSUE TITLE
Signs dont work in 1.20

### ISSUE THREAD

**Issue by BreadBod** [andrewlalis/SpeedCarts#14]
i was on a server and was trying to make a minecart track but the signs didnt change the speed. We have the speed max set to 24 but it wouldnt change how it would go with a sign would it?

**Comment by BreadBod** [comment]
does it matter what block i place the sign on or what wood the sign is?

**Comment by andrewlalis** [comment]
This mod wasn't ever compiled or released for Minecraft version 1.20, so I suppose it just doesn't work in that version. Feel free to fork the repository to update it, but I won't update it past version 1.19.1.
