### ISSUE TITLE
1.20 sign changes breaks 1.19.3 version

### ISSUE THREAD

**Issue by zndrmn** [andrewlalis/SpeedCarts#15]
The new sign changes in 1.20 breaks my 1.19.3 fork and I'm not sure how to fix it.

Though if you do work on this it seems like you might be able to detect text on either side of the sign so then maybe you could have the minecart go faster one way and slower the other way

**Comment by andrewlalis** [comment]
I don't really support this mod anymore; and for personal reasons I'm not going to update beyond 1.19.2, but there are a number of forks of this mod which you can try; some of them are probably much better.
